openapi: 3.0.0
info:
  version: "1.0.0"
  title: Vehicle Rental System API

paths:

  /vehicles:
    get:
      summary: Search for a vehicle by its name
      parameters:
        - name: name
          in: query
          description: Name of the vehicle
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '404':
          description: Vehicle not found

  /rent:
    post:
      summary: Request to rent a vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RentRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input or vehicle is not available
        '404':
          description: Member or Vehicle not found

  /return/{vehicleId}:
    post:
      summary: Return a rented vehicle
      parameters:
        - name: vehicleId
          in: path
          description: ID of the vehicle to be returned
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input or vehicle was not rented
        '404':
          description: Vehicle not found

components:
  schemas:

    Vehicle:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [Available, Rented]

    RentRequest:
      type: object
      properties:
        memberId:
          type: string
          description: ID of the member requesting the rental
        vehicleId:
          type: string
          description: ID of the vehicle to be rented
