[GLOBAL]
pants_version = "2.17.0"
backend_packages = [
  "pants.backend.shell",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.awslambda.python",
]

[python]
interpreter_constraints = ['==3.11.*']

[python-infer]
use_rust_parser = "True"

[lambdex]
layout = "zip"