python_sources()

python_awslambda(
    name="lambda",
    runtime="python3.11",
    handler="lambda_function.py:lambda_handler",
    output_path="lambda_vehicles.zip",
)

python_requirements(
    name="reqs",
)
