@startuml

class User {
    userId
    ---
}

class Vehicle {
    vehicleId
    ---
    userId
    vehicleName
    rentalDatetime
    dueDatetime
}


Vehicle "1..*" - "0..1" User
note on link 
各車両は, 貸出ユーザがいるかいないかの2択
車両を借りていないユーザは管理対象外
end note


@enduml
